import express from 'express'
import matricula from './router/matriculas.js'
import planos from './router/planos.js'
import treinos from './router/treinos.js'
import professores from './router/professores.js'